config/routes.rb
Rails.application.routes.draw do
  resources :resolutions
  get 'home/index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  get 'comments/index'
  get 'comments/show'
  get 'comments/new'
  get 'comments/edit'

  resources :posts do
     resources :comments, module: :posts
  end

  resources :resolutions do
    resources :comments, module: :resolutions
 end

 resources :resolutions do
    member do
      put "like" => "resolutions#upvote"
      put "unlike" => "resolutions#downvote"
    end
 end

  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/resolution.rb
class Resolution < ApplicationRecord
    validates:titleR, :presence=>true, :length=>{:minimum=>3}
    validates:contentR, :presence=>true 
    has_many:comments, as: :commentable
    acts_as_votable
end

app/controllers/resolutions/comments_controller.rb
class Resolutions::CommentsController < CommentsController
    before_action :set_commentable

    private

        def set_commentable
            @commentable=Resolution.find(params[:resolution_id])
        end

end

app/controllers/resolutions_controller.rb
class ResolutionsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_access, only: %i[new create edit update destroy]
  before_action :set_resolution, only: %i[ show edit update destroy upvote downvote]

  # GET /resolutions or /resolutions.json
  def index
    @resolutions = Resolution.all
  end

  # GET /resolutions/1 or /resolutions/1.json
  def show
  end

  # GET /resolutions/new
  def new
    @resolution = Resolution.new
  end

  # GET /resolutions/1/edit
  def edit
  end

  # POST /resolutions or /resolutions.json
  def create
    @resolution = Resolution.new(resolution_params)

    respond_to do |format|
      if @resolution.save
        format.html { redirect_to @resolution, notice: "Uchwała została pomyślnie utworzona." }
        format.json { render :show, status: :created, location: @resolution }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resolution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resolutions/1 or /resolutions/1.json
  def update
    respond_to do |format|
      if @resolution.update(resolution_params)
        format.html { redirect_to @resolution, notice: "Uchwała została pomyślnie zaktualizowana." }
        format.json { render :show, status: :ok, location: @resolution }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resolution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resolutions/1 or /resolutions/1.json
  def destroy
    @resolution.destroy
    respond_to do |format|
      format.html { redirect_to resolutions_url, notice: "Uchwała została pomyślnie usunięta." }
      format.json { head :no_content }
    end
  end

  def upvote
    if current_user.voted_up_on? @resolution
      @resolution.unvote_by current_user, :vote_weight => current_user.part
    else
      @resolution.upvote_by current_user, :vote_weight => current_user.part
    end
    redirect_to resolution_path
  end

  def downvote  
    if current_user.voted_down_on? @resolution
      @resolution.unvote_by current_user, :vote_weight => current_user.part
    else 
      @resolution.downvote_by current_user, :vote_weight => current_user.part
    end
    redirect_to resolution_path
  end   

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resolution
      @resolution = Resolution.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def resolution_params
      params.require(:resolution).permit(:titleR, :contentR, :votable)
    end 

end

app/helpers/resolutions_helper.rb
module ResolutionsHelper
end

app/views/resolutions/_form.html.erb
<%= form_with(model: resolution) do |form| %>
  <% if resolution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resolution.errors.count, "error") %> prohibited this resolution from being saved:</h2>

      <ul>
        <% resolution.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4 class="fw-normal"><%= form.label :titleR, "Tytuł" %></h4>
    <%= form.text_field :titleR, class:'shadow-sm fs-3' %>
  </div>

  <div class="field">
    <h4 class="fw-normal"><%= form.label :contentR, "Treść" %></h4>
    <%= form.text_area :contentR, class:'shadow-sm' %>
  </div>

  <div class="field">
    <h4 class="fw-normal">Możliwość głosowania</h4>
    <ul>
      <li>
        <%= form.radio_button :votable, true, :checked => true, class: 'radio-b' %> 
        <%= form.label :votable, "Aktywna", :value => "true" %>
      </li>
      <li>  
        <%= form.radio_button :votable, false, class: 'radio-b' %>
        <%= form.label :votable, "Nieaktywna", :value => "false" %> 
      </li>
    </ul>
  </div>

  <div class="actions">
    <%= form.submit :"Zapisz uchwałę", class:'btn link color-theme' %>
  </div>
<% end %>

app/views/resolutions/edit.html.erb
<header>
    <section id="top" class="jumbotron3 jumbotron-fluid w-100">   
    </section>
</header>

<div class="container">
    <section id="section-body">
        <h1 class="text-center display-4">Edycja uchwały</h1>

        <%= render 'form', resolution: @resolution %>

        <button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Wyświetl', @resolution, :class => 'text-decoration-none text-reset' %></button>
        <button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Cofnij', resolutions_path, :class => 'text-decoration-none text-reset' %></button>
    </section>
</div>

app/views/resolutions/index.html.erb
<header>
    <section id="top" class="jumbotron3 jumbotron-fluid w-100">   
    </section>
</header>

<div id="title" class="text-center">Uchwały</div>

<div class="container">
  <section id="section-body">
    <div class="table-responsive">
      <table id="tabela_uchwal" class="table table-hover">
        <thead>
          <tr style="background-color: #4080bf; color:beige">
            <th scope="col" class="align-middle">Tytuł</th>
            <th scope="col" class="align-middle text-center">Data utworzenia</th>
            <th scope="col"></th>
            <% if (user_signed_in?) && (current_user.email == "admin@ruby.pl") %>
              <th scope="col"></th>
              <th scope="col"></th>
            <% end %>
          </tr>
        </thead>

        <tbody>
          <% @resolutions.each do |resolution| %>
            <tr>
              <td><%= resolution.titleR %></td>
              <td class="text-center"><%= resolution.created_at.to_date %></td>
              <td class="text-center"><%= link_to 'Wyświetl', resolution, :class => 'text-reset' %></td>
              <% if (user_signed_in?) && (current_user.email == "admin@ruby.pl") %>
                <td class="text-center"><%= link_to 'Edytuj', edit_resolution_path(resolution), :class => 'text-reset' %></td>
                <td class="text-center"><%= link_to 'Usuń', resolution, method: :delete, data: { confirm: 'Czy jesteś pewien?' }, :class => 'text-reset' %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <br>

    <% if (user_signed_in?) && (current_user.email == "admin@ruby.pl") %>
      <button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Nowa uchwała', new_resolution_path, :class => 'text-decoration-none text-reset' %></button>
    <% end %>
    <button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Strona główna', home_index_path, :class => 'text-decoration-none text-reset' %></button>
  </section>
</div>

<script>
   $(document).ready(function() {
      $('#tabela_uchwal').DataTable({
         "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.21/i18n/Polish.json"
         }
      });
   });
</script>

app/views/resolutions/new.html.erb
<header>
    <section id="top" class="jumbotron3 jumbotron-fluid w-100">   
    </section>
</header>

<div class="container">
    <section id="section-body">
        <h1 class="text-center display-4">Nowa uchwała</h1>

        <%= render 'form', resolution: @resolution %>

        <button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Cofnij', resolutions_path, :class => 'text-decoration-none text-reset' %></button>
    </section>
</div>

app/views/resolutions/show.html.erb
<header>
    <section id="top" class="jumbotron3 jumbotron-fluid w-100">   
    </section>
</header>

<div class="container">
  <section id="section-body">
    <h1 class="text-center display-4 mb-3">
      <%= @resolution.titleR %>
    </h1>

    <p>
      <%= @resolution.contentR %>
    </p>

    <p class="text-end mb-1">
      Data utworzenia: <%= @resolution.created_at.to_date %>
    </p>

    <% if @resolution.updated_at? %>
      <p class="text-end">
        Data ostatniej aktualizacji: <%= @resolution.updated_at.to_date %>
      </p>
    <% end %>

  </section>
  <section id="section-voting">
    <div id="voting" class="text-center mb-3">
      <% if (@resolution.votable?) && (current_user.part != 0) %>
        <button type="button" class="btn color-theme m-2 ms-0">  
          <i class="fas fa-thumbs-up"></i>
          <%= link_to like_resolution_path(@resolution), :class => 'text-decoration-none text-reset', method: :put do %>
            Tak
            <%= @resolution.get_upvotes.size %>
          <% end %>
        </button>

        <button type="button" class="btn color-theme m-2 ms-0"> 
          <i class="fas fa-thumbs-down"></i>
          <%= link_to unlike_resolution_path(@resolution), :class => 'text-decoration-none text-reset', method: :put do %>
            Nie
            <%= @resolution.get_downvotes.size %>
          <% end %>
        </button>
      <% elsif (@resolution.votable?) && (current_user.part == 0)%>
        <button type="button" class="btn color-theme m-2 ms-0 unactive">
          <i class="fas fa-thumbs-up"></i>
          Tak
          <%= @resolution.get_upvotes.size %>
        </button>
        <button type="button" class="btn color-theme m-2 ms-0 unactive"> 
          <i class="fas fa-thumbs-down"></i>
          Nie
          <%= @resolution.get_downvotes.size %>
        </button> 
        
      <% else %>
        <button type="button" class="btn color-theme m-2 ms-0 unactive">
          <i class="fas fa-thumbs-up"></i>
          Tak
          <%= @resolution.get_upvotes.size %>
        </button>
        <button type="button" class="btn color-theme m-2 ms-0 unactive"> 
          <i class="fas fa-thumbs-down"></i>
          Nie
          <%= @resolution.get_downvotes.size %>
        </button><br/>
        <span id="glos">Głosowanie zakończone. Dziękujemy za oddane głosy.</span>
      <% end %>
    </div>

    
    <div class="table-responsive">
      <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col" class="text-center">Imie</th>
          <th scope="col" class="text-center">Nazwisko</th>
          <th scope="col" class="text-center">Udział w nieruchomości</th>
          <th scope="col" class="text-center">Głos</th>
        </tr>
      </thead>

      <tbody>
        <% @resolution.votes_for.voters.each do |voter| %>
          <tr>
            <td class="text-center"><%= voter.name %></td>
            <td class="text-center"><%= voter.surname %></td>
            <td class="text-center"><%= voter.part.to_i %>/30000</td>
            <td class="text-center"><%= if voter.voted_up_on? @resolution then "TAK" else "NIE" end %></td>  
          </tr>
        <% end %>
      </tbody>
      </table>
    </div>
    <p class="mb-1 fw-bold text-center">Ilość osób, które zagłosowały na TAK: <%= @resolution.get_upvotes.size %>, z udziałem w nieruchomości: <%= @resolution.get_upvotes(@resolution).sum(:vote_weight).to_i%>/30000</p>
    <p class="fw-bold text-center">Ilość osób, które zagłosowały na NIE: <%= @resolution.get_downvotes.size %>, z udziałem w nieruchomości: <%= @resolution.get_downvotes(@resolution).sum(:vote_weight).to_i%>/30000</p>
  </section>

  <section id="section-comments">
    <h2 class="mb-3">Komentarze</h2>
    <% @resolution.comments.each do |c| %>
      <div class="card shadow-sm mb-2 flex-row">
        <span class="ikona"><i class="fas fa-user fa-2x align-middle"></i></span>
        <div class="card-body ps-0">
          
          <span>
            <h5 class="card-title">
              <span><%=h c.commenter %><span> &nbsp <span class="fw-normal" style="font-size:11px"><%=h c.created_at.to_date %></span>
            </h5>

            <p class="card-text">
              <%=h c.body %>
            </p>
          </span>
        </div>
      </div>
    <% end %>

    <% if (user_signed_in?) && (current_user.email == "admin@ruby.pl") %>
      <button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Edytuj uchwałę', edit_resolution_path(@resolution), :class => 'text-decoration-none text-reset' %></button>
    <% end %>
    <button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Cofnij do uchwał', resolutions_path, :class => 'text-decoration-none text-reset' %></button>
    <button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Sekcja komentarzy', resolution_comments_path(@resolution), :class => 'text-decoration-none text-reset' %></button>
    <button type="button" class="btn color-theme m-2 ms-0 mt-0 d-flex"><%= link_to "Strona głowna", home_index_path, :class => 'text-decoration-none text-reset' %></button>

  </section>
</div>