config/routes.rb
Rails.application.routes.draw do
  resources :resolutions
  get 'home/index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  get 'comments/index'
  get 'comments/show'
  get 'comments/new'
  get 'comments/edit'

  resources :posts do
     resources :comments, module: :posts
  end

  resources :resolutions do
    resources :comments, module: :resolutions
 end

 resources :resolutions do
    member do
      put "like" => "resolutions#upvote"
      put "unlike" => "resolutions#downvote"
    end
 end

  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    validates:title, :presence=>true, :length=>{:minimum=>3}
    validates:content, :presence=>true 
    has_many:comments, as: :commentable
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
    before_action :set_commentable

    private

        def set_commentable
            @commentable=Post.find(params[:post_id])
        end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_access, only: %i[new create edit update destroy]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post został pomyślnie utworzony." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post został pomyślnie zaktualizowany." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post został pomyślnie usunięty." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4 class="fw-normal"><%= form.label :title, "Tytuł" %></h4>
    <%= form.text_field :title, class:'shadow-sm fs-3'  %>
  </div>

  <div class="field">
    <h4 class="fw-normal"><%= form.label :content, "Treść" %></h4>
    <%= form.text_area :content, class:'shadow-sm' %>
  </div>

  <div class="actions">
    <%= form.submit :"Zapisz post", class:'btn link color-theme' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<header>
    <section id="top" class="jumbotron2 jumbotron-fluid w-100">    
    </section>
</header>

<div class="container">
    <section id="section-body">
        <h1 class="text-center display-4">Edycja postu</h1>

        <%= render 'form', post: @post %>

        <button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Wyświetl', @post, :class => 'text-decoration-none text-reset' %></button>
        <button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Cofnij', posts_path, :class => 'text-decoration-none text-reset' %></button>
    </section>
</div>

app/views/posts/index.html.erb
<header>
    <section id="top" class="jumbotron2 jumbotron-fluid w-100">    
    </section>
</header>

<div id="title" class="text-center">Posty</div>

<div class="container">
  <section id="section-body">
    <div class="table-responsive">
      <table id="tabela_postow" class="table table-hover">
        <thead>
          <tr style="background-color: #4080bf; color:beige">
            <th scope="col" class="align-middle">Tytuł</th>
            <th scope="col" class="align-middle text-center">Data uwtorzenia</th>
            <th scope="col"></th>
            <% if (user_signed_in?) && (current_user.email == "admin@ruby.pl") %>
              <th scope="col"></th>
              <th scope="col"></th>
            <% end %>
          </tr>
        </thead>

        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td><%= post.title %></td>
              <td class="text-center"><%= post.created_at.to_date %></td>
              <td class="text-center"><%= link_to 'Wyświetl', post, :class => 'text-reset' %></td>
              <% if (user_signed_in?) && (current_user.email == "admin@ruby.pl") %>
                <td class="text-center"><%= link_to 'Edytuj', edit_post_path(post), :class => 'text-reset' %></td>
                <td class="text-center"><%= link_to 'Usuń', post, method: :delete, data: { confirm: 'Czy jesteś pewien?' }, :class => 'text-reset' %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <br>
    <% if (user_signed_in?) && (current_user.email == "admin@ruby.pl") %>
      <button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Nowy post', new_post_path, :class => 'text-decoration-none text-reset' %></button>
    <% end %>
    <button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Strona główna', home_index_path, :class => 'text-decoration-none text-reset' %></button>
  </section>
</div>

<script>
   $(document).ready(function() {
      $('#tabela_postow').DataTable({
         "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.21/i18n/Polish.json"
         }
      });
   });


</script>

app/views/posts/new.html.erb
<header>
    <section id="top" class="jumbotron2 jumbotron-fluid w-100">    
    </section>
</header>

<div class="container">
    <section id="section-body">
        <h1 class="text-center display-4">Nowy post</h1>

        <%= render 'form', post: @post %>

        <button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Cofnij', posts_path, :class => 'text-decoration-none text-reset' %></button>
    </section>
</div>

app/views/posts/show.html.erb
<header>
    <section id="top" class="jumbotron2 jumbotron-fluid w-100">    
    </section>
</header>

<div class="container">
	<section id="section-body">
		<h1 class="text-center display-4 mb-3">
			<%= @post.title %>
		</h1>

		<p>
			<%= @post.content %>
		</p>

		
		<p class="text-end mb-1">
			Data utworzenia: <%= @post.created_at.to_date %>
	  	</p>
  
		<% if @post.updated_at? %>
			<p class="text-end">
				Data ostatniej aktualizacji: <%= @post.updated_at.to_date %>
			</p>
		<% end %>

	</section>
	<section id="section-comments">
		<h2 class=" mb-3">Komentarze</h2>
		<% @post.comments.each do |c| %>
			<div class="card shadow-sm mb-2 flex-row">
				<span class="ikona"><i class="fas fa-user fa-2x align-middle"></i></span>
				<div class="card-body ps-0">
					
					<h5 class="card-title">
						<span><%=h c.commenter %></span> &nbsp <span class="fw-normal" style="font-size:11px"><%=h c.created_at.to_date %></span>
					</h5>

					<p class="card-text">
						<%=h c.body %>
					</p>

				</div>
			</div>
		<% end %>

		<% if (user_signed_in?) && (current_user.email == "admin@ruby.pl") %>
			<button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Edytuj post', edit_post_path(@post), :class => 'text-decoration-none text-reset' %></button>
		<% end %>
		<button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Cofnij do postów', posts_path, :class => 'text-decoration-none text-reset' %></button>
		<button type="button" class="btn color-theme m-2 ms-0"><%= link_to 'Sekcja komentarzy', post_comments_path(@post), :class => 'text-decoration-none text-reset' %></button>
		<button type="button" class="btn color-theme m-2 ms-0 mt-0 d-flex"><%= link_to "Strona głowna", home_index_path, :class => 'text-decoration-none text-reset' %></button>
	</section>
</div>